output:
  directory: "output"
  format: "PNG"
  resolution: [800, 800]
  samples: 128

cube:
  size: 2
  location: [0, 0, 0]
  material:
    metallic: 1.0
    roughness: 0.04
    specular: 1.0

environment:
  hdri_path: "assets/paris.exr" 

camera:
  num_images: 60
  distance: 5.0
  elevation_angles: [-60, -30, 0, 30, 60]