output:
  directory: "output"
  format: "PNG"
  resolution: [800, 800]
  samples: 128

cube:
  size: 1
  location: [0, 0, 0]
  bevel_width: 0.5
  bevel_segments: 5
  bevel_profile: 0.7
  bump_strength: 0.05
  material:
    metallic: 1.0
    roughness: 0.1
    specular: 0.5

environment:
  hdri_path: "assets/paris.exr"

camera:
  num_images: 300
  theta_max_deg: 85
  distance: 5.0